# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='strain',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terpene',
            name='aroma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='terpene',
            name='effects',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='terpene',
            name='flavor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='terpene',
            name='long_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terpene',
            name='short_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
