# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0002_auto_20160129_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terpene',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
