# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0003_auto_20160129_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qasample',
            name='sample_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='terpeneresult',
            unique_together=set([('qa_sample', 'terpene')]),
        ),
    ]
