# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0004_auto_20160129_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
