# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0005_strain_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potencyresult',
            old_name='result',
            new_name='cbc',
        ),
        migrations.RemoveField(
            model_name='potencyresult',
            name='name',
        ),
        migrations.RemoveField(
            model_name='potencyresult',
            name='qa_sample',
        ),
        migrations.AddField(
            model_name='potencyresult',
            name='cbd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potencyresult',
            name='cbg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potencyresult',
            name='cbn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potencyresult',
            name='delta8_thc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potencyresult',
            name='delta9_thc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potencyresult',
            name='total_cannabinoids',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potencyresult',
            name='total_thc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
