# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0006_auto_20160129_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='potencyresult',
            name='qa_sample',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='strains.qaSample'),
            preserve_default=False,
        ),
    ]
