# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0007_potencyresult_qa_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potencyresult',
            name='qa_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strains.qaSample', unique=True),
        ),
    ]
