# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='header',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
