# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=35)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AboutUsPage')),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Sections',
            },
        ),
    ]
