# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carouselimage_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosection',
            name='text',
            field=models.TextField(default='PHASELLUS FRINGILLA VEHICULA EGESTAS. CLASS APTENT TACITI SOCIOSQU AD LITORA TORQUENT PER CONUBIA NOSTRA, PER INCEPTOS HIMENAEOS'),
            preserve_default=False,
        ),
    ]
