# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_infosection_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='homepage',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
