# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_retailercontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandsection',
            options={'verbose_name': 'Brand Section', 'verbose_name_plural': 'Brand Section'},
        ),
        migrations.AlterModelOptions(
            name='infosection',
            options={'verbose_name': 'Info Section', 'verbose_name_plural': 'Info Section'},
        ),
        migrations.AlterModelOptions(
            name='newslettercontact',
            options={'verbose_name': 'Newsletter Contact', 'verbose_name_plural': 'Newsletter Contacts'},
        ),
        migrations.AlterModelOptions(
            name='retailercontact',
            options={'verbose_name': 'Retailer Contact', 'verbose_name_plural': 'Retailer Contacts'},
        ),
        migrations.AlterField(
            model_name='retailercontact',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
